version: '3.6'

networks:
  net_testing_env:
    driver: bridge
    ipam:
      config:
        - subnet: 172.29.30.0/24 # Specify subnet

services:
  zookeeper:
    image: 'bitnami/zookeeper:3.7'
    container_name: zookeeper
    hostname: zookeeper
    networks:
      - net_testing_env
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:3.1'
    container_name: kafka
    hostname: kafka
    networks:
      - net_testing_env
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  elasticsearch:
    image: 'elasticsearch:7.9.3'
    container_name: elasticsearch
    hostname: elasticsearch
    ports:
      - '19200:9200'
    environment:
      - discovery.type=single-node
    networks:
      - net_testing_env

  nimbus:
    image: storm:2.4.0
    container_name: nimbus
    hostname: nimbus
    command: storm nimbus -c topology.worker.max.heap.size.mb=65536 -c worker.heap.memory.mb=65536
    depends_on:
      - zookeeper
    links:
      - zookeeper
    restart: always
    ports:
      - 6627:6627
    networks:
      - net_testing_env

  supervisor:
    image: storm:2.4.0
    container_name: supervisor
    hostname: supervisor
    command: storm supervisor -c worker.heap.memory.mb=65536 -c supervisor.memory.capacity.mb=262144 -c worker.profiler.enabled=true
    depends_on:
      - nimbus
      - zookeeper
    links:
      - nimbus
      - zookeeper
    restart: always
    volumes:
      - ${SR_DIR:-/tmp/selective-reprocessing}/storm-conf/topology-single.properties:/tmp/topology-single.properties
      - ${SR_DIR:-/tmp/selective-reprocessing}/storm-conf/sr-storm-1.0.0-dep.jar:/tmp/sr-storm-1.0.0-dep.jar
    networks:
      - net_testing_env

  storm_ui:
    image: storm:2.4.0
    container_name: ui
    hostname: ui
    command: storm ui
    depends_on:
      - nimbus
    links:
      - nimbus
    restart: always
    ports:
      - 8080:8080
    networks:
      - net_testing_env

  tomcat:
    image: tomcat:8.5.99-jdk8
    container_name: tomcat
    hostname: tomcat
    restart: always
    ports:
      - 8080:8080
    networks:
      - net_testing_env

